### ISSUE TITLE
bar disappears when applying the patch

### ISSUE THREAD

**Issue by vk0xOrg** [mihirlad55/dwm-anybar#3]
the title says it all. When applying this patch and reloading DWM bar disappears. It doesn't show up no matter what configs are used for bar (top/bottom, alternative/native).
I wasn't able to trance nor trace any error no find what's going wrong.
How could I resolve the issue?

**Comment by mihirlad55** [comment]
Does this patch work with your external status bar? I just noticed that `usealtbar = 0` was not properly implemented. It should be fixed in v1.1.1 which I just released. If this was just an issue with dwm's status bar not working, please try the updated patch. If there is an issue with your external/alternate status bar not working, let me know.

See commits:
2f5178c2af08cd0638b822c7ccd5a9987ea08ff7
8026a9c2c9fc044badb3305bfec1a1b83be4b6de

See release:
https://github.com/mihirlad55/dwm-anybar/releases/tag/v1.1.1

**Comment by vk0xOrg** [comment]
@mihirlad55 nope, it doesn't work. I've tested with & without `polybar tray fix`. When setting is ```usealtbar=1``` DWM's status bar disappears and only polybar is displayed without DWM's tags. Should this be running in that way?

[Here is](https://framagit.org/mambojambo/own-dwm/-/tree/anybar) my build of ```anybar patch```

**Comment by mihirlad55** [comment]
This is the purpose of the patch: to replace dwm's bar with an external status bar program. This is the intended behavior. However, polybar should be showing DWM's tags if you have it configured to. If there is an issue with `polybar-dwm-module`, it should be reported at https://github.com/mihirlad55/polybar-dwm-module

**Comment by vk0xOrg** [comment]
ok, what I've done so far:
 - applied new release (v1.1.1) of `anybar` patch. After that DWM's status bar stayed in the place where it should be if `usealtbar = 0`
- applied `IPC` patch
- installed `polybar-dwm-module`.

This issue is resolved  by the new release, so I'm clothing it. However, there is an issue re `polybar-dwm-module` which would be reported separatly
