### ISSUE TITLE
Patching failed

### ISSUE THREAD

**Issue by addy419** [mihirlad55/dwm-anybar#9]
Patching dwm 6.2 with default config and no other patches fails for https://dwm.suckless.org/patches/anybar/dwm-anybar-polybar-tray-fix-20200810-bb2e722.diff at hunk #13 or https://dwm.suckless.org/patches/anybar/dwm-anybar-20200810-bb2e722.diff at hunk #10
The only changes in default config.def.h are
```c
static const int usealtbar     			= 1;        /* 1 means use non-dwm status bar */
static const char *altbarclass 			= "Polybar";/* Alternate bar class name */
```

Edit: same happens for https://github.com/mihirlad55/dwm-anybar/releases/download/v1.1.1/dwm-anybar-polybar-tray-fix-20200905-bb2e722.diff hunk #13 at 713

**Comment by mihirlad55** [comment]
Sorry for the late reply. Those patches fails because those patches are meant for specific dwm commits made after version 6.2. Due to the amount of extra time required to maintain the patch for two separate version histories (one being a stable release version, and the other being the latest commit), I've decided that I will only release patches for the latest commit. In the future, this commit may happen to be a stable release version in which case it's a win-win situation as long as the `anybar` patch does not receive additional features for commits after the stable release commit.

If anyone has a simple and efficient solution for maintaining the patch for two separate version histories, I'm open to ideas. However, for now I will close this issue.
